[project]
name = "my-adk-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-adk>=2.5.0",
    "google-cloud-bigquery>=3.42.2",
    "mcp[cli]>=1.28,<2",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
    "sentence-transformers>=5.6.0",
    "toolbox-core>=1.2.0",
]
